name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          sudo usermod -aG docker $USER
          sudo systemctl restart docker

      - name: Build Docker image
        run: |
          docker build -t go-app-image .

      - name: Run Docker container
        run: |
          docker run -p 8080:8080 go-app-image
