name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: docker-practice/actions-setup-docker@master
        with:
          context: ./app
          file: ./Dockerfile

      - name: Set up Docker
        run: |
          sudo apt-get update
          docker version
          sudo usermod -aG docker $USER
          sudo systemctl restart docker

      - name: Build Docker image
        run: |
          docker build -t go-app-image .

      - name: Run Docker container
        run: |
          docker run -p 8080:8080 go-app-image
