
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Go version
        run: |
          go run test.go
          echo "building go app